// packages/next-blog/components/sections/HeroContent.tsx
import { useEffect, useRef } from "react"
import { ArrowRightIcon } from "@radix-ui/react-icons"
import { gsap } from "gsap"
import { ScrollTrigger } from "gsap/dist/ScrollTrigger"
import Link from "next/link"

export default function HeroContent() {
  const sectionRef = useRef(null)
  const q = gsap.utils.selector(sectionRef)

  useEffect(() => {
    gsap.registerPlugin(ScrollTrigger)

    const textAnimationTimeline = gsap.timeline({
      defaults: { stagger: 0.2, duration: 0.3 },
    })

    textAnimationTimeline.fromTo(
      q(".text-animation"),
      {
        y: 100,
      },
      {
        y: 0,
        delay: 2.2,
      }
    )
    textAnimationTimeline.fromTo(
      ".bio-animation ",
      {
        scale: 0,
      },
      {
        scale: 1,
        ease: "back",
        duration: 0.3,
      }
    )
  }, [q])

  return (
    <div
      ref={sectionRef}
      className="absolute max-w-[55rem] m-auto w-full top-[20%] md:top-[50%] left-[50%] -translate-x-1/2 md:-translate-y-1/2 flex flex-col gap-4 justify-center items-center"
    >
      <div className="overflow-hidden">
        <div className="text-animation  dark:bg-[linear-gradient(#fff,rgba(255,255,255,.6))] inline-block text-black dark:text-transparent bg-clip-text leading-none text-4xl md:text-6xl font-semibold">
          Welcome to
        </div>
      </div>

      <div className="overflow-hidden">
        <div className="text-animation text-2xl md:text-4xl font-semibold">
          <span className="text-accentColor">X-press</span>
          {/* <span className="bg-[linear-gradient(#fff,rgba(255,255,255,.6))] inline-block text-transparent bg-clip-text">
            A Stage as a
          </span>{" "}
          <span className="text-accentColor">Front-End</span>{" "}
          <span className="bg-[linear-gradient(#000000,rgba(255,255,255,.6))] dark:bg-[linear-gradient(#fff,rgba(255,255,255,.6))] inline-block text-transparent bg-clip-text">
            Developer
          </span> */}
        </div>
      </div>

      <div className="w-[300px] md:w-[370px] relative z-30 text-center text-sm dark:bg-[linear-gradient(#fff,rgba(255,255,255,.6))] inline-block text-black dark:text-transparent bg-clip-text"></div>

      <div className="bio-animation dark:bg-[linear-gradient(#fff,rgba(255,255,255,.6))] inline-block text-black dark:text-transparent bg-clip-text text-md md:text-lg">
        A stage where enthusiasm meets technology.
      </div>

      <Link
        href="#contact"
        aria-label="Contact Me"
        className="contact_me_btn px-4 py-[6px] shadow-md mt-10 md:mt-3 group flex items-center gap-2"
      >
        <div className="dark:text-black relative z-[3] text-sm">Contact Me</div>
        <div className="sr-only">Contact Me</div>
        <div className="contact_me_btn_overlay group-hover:opacity-100" />
        <div className="relative group overflow-hidden w-4 z-[3]">
          <div className="flex group-hover:animate-animate-frame-contact-me-btn-icon translate-x-[-100%]">
            <ArrowRightIcon className="text-black flex-none relative z-[3]" />
            <ArrowRightIcon className="text-black flex-none relative z-[3]" />
          </div>
        </div>
      </Link>
    </div>
  )
}

// .vitepress/theme/components/portfolio/HeroContent.vue
<script lang="ts" setup>
import { ref } from 'vue'
import { useGsapAnimation } from '../../composables/useGsapAnimation'

const sectionRef = ref<HTMLElement | null>(null)

useGsapAnimation(sectionRef, {
  setup({ gsap }) {
    const tl = gsap.timeline({
      defaults: { stagger: 0.2, duration: 0.3 },
    })

    tl.fromTo(
      '.text-animation',
      { y: 100 },
      { y: 0, delay: 2.2 }
    )

    tl.fromTo(
      '.bio-animation',
      { scale: 0 },
      { scale: 1, ease: 'back', duration: 0.3 }
    )

    return tl
  },
})
</script>

<template>
  <div
    ref="sectionRef"
    class="absolute max-w-[55rem] m-auto w-full top-[20%] md:top-1/2 left-1/2 -translate-x-1/2 md:-translate-y-1/2 flex flex-col gap-4 justify-center items-center"
  >
    <!-- Title: "Welcome to" -->
    <div class="overflow-hidden">
      <div
        class="text-animation dark:bg-[linear-gradient(#fff,rgba(255,255,255,.6))] inline-block text-black dark:text-transparent bg-clip-text leading-none text-4xl md:text-6xl font-semibold"
      >
        Welcome to
      </div>
    </div>

    <!-- Subtitle: "X-press" -->
    <div class="overflow-hidden">
      <div class="text-animation text-2xl md:text-4xl font-semibold">
        <span class="text-accentColor">X-press</span>
      </div>
    </div>

    <!-- Spacer (matches original empty div) -->
    <div
      class="w-[300px] md:w-[370px] relative z-30 text-center text-sm dark:bg-[linear-gradient(#fff,rgba(255,255,255,.6))] inline-block text-black dark:text-transparent bg-clip-text"
    />

    <!-- Bio tagline -->
    <div
      class="bio-animation dark:bg-[linear-gradient(#fff,rgba(255,255,255,.6))] inline-block text-black dark:text-transparent bg-clip-text text-md md:text-lg"
    >
      A stage where enthusiasm meets technology.
    </div>

    <!-- Contact Me button -->
    <a
      href="#contact"
      aria-label="Contact Me"
      class="contact_me_btn px-4 py-[6px] shadow-md mt-10 md:mt-3 group flex items-center gap-2"
    >
      <div class="dark:text-black relative z-[3] text-sm">Contact Me</div>
      <span class="sr-only">Contact Me</span>
      <div class="contact_me_btn_overlay group-hover:opacity-100" />
      <div class="relative group overflow-hidden w-4 z-[3]">
        <div class="flex group-hover:animate-[frame-contact-me-btn-icon_.3s_ease] translate-x-[-100%]">
          <!-- Arrow right icon (inline SVG replacing @radix-ui/react-icons ArrowRightIcon) -->
          <svg
            class="text-black flex-none relative z-[3]"
            width="15"
            height="15"
            viewBox="0 0 15 15"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M8.14645 3.14645C8.34171 2.95118 8.65829 2.95118 8.85355 3.14645L12.8536 7.14645C13.0488 7.34171 13.0488 7.65829 12.8536 7.85355L8.85355 11.8536C8.65829 12.0488 8.34171 12.0488 8.14645 11.8536C7.95118 11.6583 7.95118 11.3417 8.14645 11.1464L11.2929 8H2.5C2.22386 8 2 7.77614 2 7.5C2 7.22386 2.22386 7 2.5 7H11.2929L8.14645 3.85355C7.95118 3.65829 7.95118 3.34171 8.14645 3.14645Z"
              fill="currentColor"
              fill-rule="evenodd"
              clip-rule="evenodd"
            />
          </svg>
          <svg
            class="text-black flex-none relative z-[3]"
            width="15"
            height="15"
            viewBox="0 0 15 15"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M8.14645 3.14645C8.34171 2.95118 8.65829 2.95118 8.85355 3.14645L12.8536 7.14645C13.0488 7.34171 13.0488 7.65829 12.8536 7.85355L8.85355 11.8536C8.65829 12.0488 8.34171 12.0488 8.14645 11.8536C7.95118 11.6583 7.95118 11.3417 8.14645 11.1464L11.2929 8H2.5C2.22386 8 2 7.77614 2 7.5C2 7.22386 2.22386 7 2.5 7H11.2929L8.14645 3.85355C7.95118 3.65829 7.95118 3.34171 8.14645 3.14645Z"
              fill="currentColor"
              fill-rule="evenodd"
              clip-rule="evenodd"
            />
          </svg>
        </div>
      </div>
    </a>
  </div>
</template>
