// packages/next-blog/components/sections/ProjectSection.tsx
"use client"

import { useEffect, useRef } from "react"
import useOnScreen from "@/hooks/useOnScreen"
import useScrollActive from "@/hooks/useScrollActive"
import HostsWitchImage from "@/public/assets/projects/HostsWitch.png"
import XPressImage from "@/public/assets/projects/X-press.png"
import VueDemiImage from "@/public/assets/projects/vue-demi.png"
import { useSectionStore } from "@/store/section"
import { gsap } from "gsap"
import { ScrollTrigger } from "gsap/dist/ScrollTrigger"
import { StaticImageData } from "next/image"
import Link from "next/link"
import { RoughNotation } from "react-rough-notation"
import ProjectCard from "../ProjectCard"

export default function ProjectSection() {
  gsap.registerPlugin(ScrollTrigger)

  const sectionRef = useRef(null)

  const elementRef = useRef<HTMLDivElement>(null)
  const isOnScreen = useOnScreen(elementRef)

  useEffect(() => {
    const q = gsap.utils.selector(sectionRef)

    gsap.timeline({
      scrollTrigger: {
        trigger: sectionRef.current,
        scrub: true,
        onEnter: () => {
          gsap.fromTo(
            q(".qoutes-animation"),
            {
              y: "-200%",
            },
            {
              y: 0,
            }
          )
        },
      },
    })
  }, [])

  // Set Active Session
  const projectSectionOnView = useScrollActive(sectionRef)
  const { setSection } = useSectionStore()

  useEffect(() => {
    projectSectionOnView && setSection("#project")
  }, [projectSectionOnView, setSection])

  return (
    <section
      ref={sectionRef}
      id="project"
      className="relative h-full bg-gray-50 dark:bg-gray-100 overflow-hidden py-14 px-10 lg:px-[5%]"
    >
      <div className="w-full max-w-[1100px] h-full m-auto flex flex-col items-center gap-14">
        <div className="w-[80%] md:w-full flex absolute left-1/2 -translate-x-1/2 flex-col gap-8 items-center">
          <RoughNotation
            type="underline"
            strokeWidth={2}
            color="hsl(157, 87%, 41%)"
            order={1}
            show={isOnScreen}
          >
            <div className="text-xl md:text-4xl tracking-tight font-medium w-fit dark:text-accentColor">
              Featured Projects
            </div>
          </RoughNotation>
          <div ref={elementRef} className="overflow-hidden ">
            <div className="qoutes-animation  md:w-full text-center font-medium flex flex-col items-center">
              <div>
                OpenSource is not about community, it&apos;s about attitude.
              </div>
            </div>
          </div>
        </div>
        <div className="w-full pt-40 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
          {projects.map((project) => (
            <ProjectCard key={project.id} item={project} />
          ))}
        </div>

        <div className="font-medium">
          Explore more projects in{" "}
          <Link
            href="https://github.com/ShinnTNT"
            target="_blank"
            aria-label="Expore more in my github profile"
            rel="noopener noreferrer"
            className="text-accentColor"
          >
            my github profile
          </Link>
        </div>
      </div>
    </section>
  )
}

export interface Project {
  id: number
  title: string
  description: string
  techStacks: string[]
  image: StaticImageData
  githubURL: string
  githubApi: string
}

const projects: Project[] = [
  {
    id: 1,
    title: "HostsExtension",
    description:
      "Enjoy the very fast and instant host-switching experience with ✨HostsWitch✨ !",
    techStacks: ["React", "TypeScript", "MUI", "Jotai"],
    image: HostsWitchImage,
    githubURL: "https://github.com/X-sky/HostsWitch",
    githubApi: "https://api.github.com/repos/X-sky/HostsWitch",
  },
  {
    id: 2,
    title: "Vue uni ui",
    description: "A Universal component lib for Vue 2 & 3!",
    techStacks: ["Vue", "typescript", "vite"],
    image: VueDemiImage,
    githubURL: "https://github.com/X-sky/vue-uni-component",
    githubApi: "https://api.github.com/repos/X-sky/vue-uni-component",
  },
  {
    id: 3,
    title: "X-press",
    description:
      "A refined and enhanced showcase of my work, an entry to all of my technique precipitation",
    techStacks: ["NextJS", "ShadnUI", "GSAP"],
    image: XPressImage,
    githubURL: "https://github.com/ShinnTNT/shinthant.dev",
    githubApi: "https://api.github.com/repos/ShinnTNT/shinthant.dev",
  },
]

// .vitepress/theme/components/portfolio/ProjectSection.vue
<script lang="ts" setup>
/**
 * ProjectSection.vue
 *
 * Migrated from X-portfolio-main/components/sections/ProjectSection.tsx
 *
 * Project showcase section for the portfolio landing page.
 * - Section id="project" for anchor navigation
 * - Displays 3 project cards in a responsive grid (1 col mobile, 2 col md, 3 col lg)
 * - Scroll-triggered quote slide-in animation via useGsapAnimation
 * - "Explore more" link points to GitHub profile
 * - Title with underline decoration matching the original design
 */
import { ref } from 'vue'
import { useGsapAnimation } from '../../composables/useGsapAnimation'
import { useScrollActive } from '../../composables/useScrollActive'
import ProjectCard from './ProjectCard.vue'
import { projects } from '../../data/projects'

const sectionRef = ref<HTMLElement | null>(null)
const titleRef = ref<HTMLElement | null>(null)

// Track visibility for navigation highlighting
const _isActive = useScrollActive(sectionRef)

useGsapAnimation(sectionRef, {
  setup({ el, gsap }) {
    gsap.timeline({
      scrollTrigger: {
        trigger: el,
        scrub: true,
        onEnter: () => {
          gsap.fromTo(
            el.querySelectorAll('.qoutes-animation'),
            { y: '-200%' },
            { y: 0 },
          )
        },
      },
    })
  },
})
</script>

<template>
  <section
    ref="sectionRef"
    id="project"
    class="relative h-full bg-gray-50 dark:bg-gray-100 dark:bg-opacity-5 overflow-hidden py-14 px-10 lg:px-[5%]"
  >
    <div class="w-full max-w-[1100px] h-full m-auto flex flex-col items-center gap-14">
      <!-- Section heading -->
      <div class="w-[80%] md:w-full flex absolute left-1/2 -translate-x-1/2 flex-col gap-8 items-center">
        <div
          ref="titleRef"
          class="text-xl md:text-4xl tracking-tight font-medium w-fit dark:text-accentColor"
          style="text-decoration: underline; text-decoration-color: hsl(157, 87%, 41%); text-underline-offset: 4px; text-decoration-thickness: 2px;"
        >
          Featured Projects
        </div>

        <!-- Animated quote -->
        <div class="overflow-hidden">
          <div class="qoutes-animation md:w-full text-center font-medium flex flex-col items-center dark:text-white">
            <div>OpenSource is not about community, it&apos;s about attitude.</div>
          </div>
        </div>
      </div>

      <!-- Project cards grid -->
      <div class="w-full pt-40 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
        <ProjectCard
          v-for="project in projects"
          :key="project.id"
          :item="project"
        />
      </div>

      <!-- Explore more link -->
      <div class="font-medium dark:text-white">
        Explore more projects in
        <a
          href="https://github.com/ShinnTNT"
          target="_blank"
          aria-label="Explore more in my github profile"
          rel="noopener noreferrer"
          class="text-accentColor no-underline hover:underline"
        >
          my github profile
        </a>
      </div>
    </div>
  </section>
</template>
